[project]
name = "darzi-backend-api"
version = "0.1.0"
dependencies = [
    "fastapi",
    "fastmcp",
    "uvicorn",
    "PyPDF2==3.0.1",
    "spacy>=3.7.0,<4.0.0",
]
readme = "README.md"
requires-python = ">=3.11"

[dependency-groups]
dev = ["pytest"]